# Experiment case
sector_exp: true
exp_name: Sector_MUnet
#exp_name: Sector_Unet
#exp_name: Sector_MUnet_MMPN
#exp_name: Sector_Unet_MMPN


# DATASET & LOADER
data_path: '/root/dataset/kitti/sequences/'
checkpoints_path: "/root/dataset/kitti/checkpoints/"
evaluation_path: "/root/dataset/kitti/evaluation/"

#data_path: '/home/dong/dataset/sequences/'
#checkpoints_path: "/home/dong/dataset/checkpoints/"
#evaluation_path: "/home/dong/dataset/evaluation/"

pc_folder: 'pc_uneven'
#pc_folder: 'velodyne'
lb_folder: 'labels_sector_1220'

lidar_height: 1.733
max_points: 100000  # max points in a scan
num_workers: 24
pc_round_range: [3.0 , 50.0, -2.0, 6.0]  # 3< r < 50 ;  -2 < z < 4
max_points_in_sector: 100
max_sectors: 10000

# FEATURE EXTRACTOR
input_features: 9
pseudo_features: 32

# MODEL PARAMETER

batch_size: 12
num_gpus: 1
epochs: 25
save_checkpoints: true
base_lr: 0.001
weight_decay: 0.00000001
momentum: 0.9
#clip: 0.25 # gradient clipping

# RESULT DISPLAY
print_freq: 10


